version: "3"
services:
  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: achatdb
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: 
  application:
    image: achat
    build: .
    restart: always
    depends_on:
      - mysqldb
    ports:
      - 8089:8089
