version: "3"
services:

  mysqldb:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    volumes:
      - db:/var/lib/mysql

  backend:
    image: achat-backend
    build: .
    ports:
      - 8089:8089
    depends_on:
      - mysqldb

volumes:
  db:
